mfoo/libyear-maven-plugin

- pom.xml
- src/main/java/com/mfoot/mojo/libyear/LibYearMojo.java
- src/site/site.xml
- src/test/java/com/mfoot/mojo/libyear/LibYearMojoTest.java
Partially delivers https://github.com/mfoo/libyear-maven-plugin/issues/2 - this PR generates a plugin documentation site when running `mvn site`. It's not hosted anywhere yet, and the JavaDoc needs work, but it's functional. I've also removed some configuration options taken from the MojoHaus show-dependency-updates mojo until I can add test coverage for them.
> Use the Maven Site Plugin to generate a plugin documentation site

- pom.xml
The maven project ecosystem uses SLF4J, and this project inherits an `slf4j-api` dependency. It doesn't inherit a logger implementation though (and it shouldn't), so currently running JUnit tests produces the following output:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
This MR fixes this by adding a logger implementation, in this case `slf4j-simple` in the `test` scope.
> Add logger implementation for tests

- pom.xml
This MR adds the `dependency:analyze-only` goal as an execution that enforces we:
- Declare dependencies we use
- Remove dependencies we don't use
- Ensure dependencies only used in tests are given `<scope>test</scope>`
> Enforce explicit declaration of all dependencies

- pom.xml
- src/main/java/com/mfoot/mojo/libyear/LibYearMojo.java
- src/test/java/com/mfoot/mojo/libyear/LibYearMojoTest.java
The Maven Search API fails fairly regularly, presumably due to poor loadbalancing health. This MR changes from the Java HTTP client to the Apache HTTP client which retries by default. It also adds better testing for server error responses and timeouts.
Technically this might allow the project to build on JDK8, but since it's EOL ideally it's not something the project should support (though a lot of projects are still stuck on old JDKs).
One concern is that the plugin could be abusing the API. There's no usage guidelines and its use will be far below other clients, but perhaps some rate limiting should be added to requests.
> Switch to Apache Maven HTTP Client and implement retry behaviour

- src/main/java/com/mfoot/mojo/libyear/LibYearMojo.java
- src/test/java/com/mfoot/mojo/libyear/LibYearMojoTest.java
Ensures the output is sorted by groupId and artifactId.
Note: this looks like it accidentally introduces some whitespace consistency. Those will be fixed once I enforce a format.
> Sort dependency updates alphabetically by groupId:artifactId in output

- README.md
- pom.xml
- src/it/basic-single-dependency-with-version-in-property/invoker.properties
- src/it/basic-single-dependency/invoker.properties
- src/it/dependency-defined-twice/invoker.properties
- src/it/dependency-defined-twice/pom.xml
- src/it/no-dependencies/invoker.properties
- src/main/java/com/mfoot/mojo/libyear/LibYearMojo.java
Since the plugin is called `libyear-maven-plugin`, Maven will automatically add the prefix `libyear:analyze`, but when called directly from the command line we just need `analyze`.
This change makes it sound less like a report, which is a keyword in Maven, used for generating HTML output for documentation.
> Rename mojo from libyear-report to analyze - resolves #17

- pom.xml
- src/main/java/com/mfoot/mojo/libyear/LibYearMojo.java
- src/test/java/com/mfoot/mojo/libyear/InMemoryTestLogger.java
- src/test/java/com/mfoot/mojo/libyear/LibYearMojoTest.java
- src/test/java/com/mfoot/mojo/libyear/MavenProjectBuilder.java
Adds the [Spotless Maven Plugin](https://github.com/diffplug/spotless/tree/main/plugin-maven) to do code formatting. Uses the [Palantir java code format](https://github.com/palantir/palantir-java-format).
The plugin is bound to the compile phase, so any local build will run the formatter.
> Add the spotless plugin for the Palantir Code Formatter

- README.md
- pom.xml
- src/main/java/com/github/mfoo/libyear/LibYearMojo.java
- src/test/java/com/github/mfoo/libyear/InMemoryTestLogger.java
- src/test/java/com/github/mfoo/libyear/LibYearMojoTest.java
- src/test/java/com/github/mfoo/libyear/MavenProjectBuilder.java
Since this project is hosted on GitHub, the package name should point people back to this project for documentation and code sources.
> Rename groupId to com.github.mfoo

- pom.xml
This doesn't seem to be needed.
Docs: https://maven.apache.org/ref/3.8.7/maven-compat/
> Plugins should avoid these classes and be updated to use only Maven3 dependencies (and require Maven3)
> Remove the maven-compat dependency

- src/main/java/com/github/mfoo/libyear/LibYearMojo.java
- src/test/java/com/github/mfoo/libyear/LibYearMojoTest.java
This PR makes two changes.
Firstly, it fixes a bug where the entire project libyears behind message was printed for each child in multi-module projects.
Secondly, it fixes a bug where the current project libyears behind message was printed for each section (e.g. dependencies, plugins, dependency management) rather than for each project.
> Logging fixes

- src/main/java/com/github/mfoo/libyear/LibYearMojo.java
- src/test/java/com/github/mfoo/libyear/LibYearMojoTest.java
The plugin makes lots of requests so it makes sense to reuse the client for performance reasons. This commit also adds a thread-safe connection pool.
> Use a shared Apache HttpClient instance

- src/main/java/com/github/mfoo/libyear/LibYearMojo.java
- src/test/java/com/github/mfoo/libyear/LibYearMojoTest.java
This MR adds a statement to the summary at the end which shows which of the projects was the oldest, and which was the most outdated dependency.
The summary only shows in a multi-module project.
Output example:
```
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   ch.qos.logback:logback-classic ......................... 0.90 libyears
<snip>
[INFO]
[INFO] This project is 50.58 libyears behind
[INFO]
[INFO] The project as a whole is 1920.60 libyears behind
[INFO] The oldest module is Test Project (299.63 libyears behind)
[INFO] The oldest dependency is com.icegreen:greenmail (13.52 libyears behind)
```
> Identify the most outdated project at the end of the build

- README.md
- pom.xml
- src/main/java/io/github/mfoo/libyear/LibYearMojo.java
- src/test/java/io/github/mfoo/libyear/InMemoryTestLogger.java
- src/test/java/io/github/mfoo/libyear/LibYearMojoTest.java
- src/test/java/io/github/mfoo/libyear/MavenProjectBuilder.java
This is part of the Sonatype requirements for publishing packages to Maven central
> Refactor groupId from com.github.mfoo to io.github.mfoo

- .github/workflows/sonar.yml
- pom.xml
This adds CI-based SonarCloud scanning based on the official instructions inside SonarCloud.
I'm raising the PR now, and hopefully this works, but I'm skeptical that it'll include any JUnit coverage because I don't have JaCoCo as a dependency in `pom.xml`.
> Add CI-based SonarCloud scanning

- src/main/java/io/github/mfoo/libyear/LibYearMojo.java
Technically unnecessary as we're guaranteed to have a value here, but SonarQube and IDEs don't know that.
This should fix the two "Bug" level issues in SonarCloud that are currently causing the quality gate to fail.
> Check if optional values are present before using.

- pom.xml
It turns out that the GitHub Packages maven repository isn't publicly accessible.
> Move <dependencyManagement> to Maven Central from GitHub Packages

- .github/workflows/maven-tests.yml
This MR bumps the test JDKs to the current LTS releases. Effectively it drops 18 and adds 21.
> chore(ci): update the JDKs used for tests to the LTS JDK versions

- .github/workflows/maven-tests.yml
Bump the build image from `ubuntu:22.04` to the latest LTS version, `ubuntu:24.04`
> chore(ci): bump build image to latest Ubuntu LTS release

- pom.xml
- src/main/java/io/github/mfoo/libyear/LibYearMojo.java
- src/test/java/io/github/mfoo/libyear/LibYearMojoTest.java
This MR replaces the Apache HTTP Client v4 with v5 per the [upgrade guide](https://hc.apache.org/httpcomponents-client-5.5.x/migration-guide/preparation.html).
It also adds an additional test case for a minor coverage improvement (error handling).
> fix: upgrade Apache HTTP Client from 4 -> 5

- pom.xml
This MR adds plugin configuration that will fail the build when a dependency is defined twice. Example output:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE                                                              
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.372 s                                                       
[INFO] Finished at: 2025-06-18T06:29:41+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.5.0:enforce (enforce-no-duplicate-dependencies) on project libyear-maven-plugin: 
[ERROR] Rule 0: …
```
> chore: disallow duplicate dependencies

- pom.xml
The Apache httpclient dependency upgrades are necessary. It seems wiremock is calling methods that don't exist in the older version that the project was using.
> chore(deps): move to newer Wiremock coordinates and upgrade

- src/it/version-uses-project.version-property/invoker.properties
- src/it/version-uses-project.version-property/pom.xml
- src/it/version-uses-project.version-property/verify.groovy
- src/main/java/io/github/mfoo/libyear/LibYearMojo.java
Currently the following is printed on the console:
```
[ERROR] Failed to fetch release date for org.apache.commons:commons-text ${project.version}: Illegal character in query at index 92: https://search.maven.org/solrsearch/select?q=g:org.apache.commons+AND+a:commons-text+AND+v:${project.version}&wt=json
```
This happens when we look up the dependencyManagement version by querying Maven, but we don't interpolate the variable. Properties defined in `<properties />` work, but not "magic" Maven versions.
> fix: prevent errors when ${project.properties} is used inside <dependencyManagement />

- .github/workflows/commit-lint.yml
This is unnecessary since code can only enter main via an MR.
> chore: don't run commitlint on main
